### ISSUE TITLE
Merge with content generator 

### ISSUE THREAD

**Issue by timuric** [iansilber/sketch-image-replace#1]
Awesome plugin! I am maintainer of content generator, and I am being asked almost daily about adding custom paths, your plugin would be a fantastic addition to the CG. Would you consider adding it to the CG repo?

**Comment by iansilber** [comment]
Yes - happy to see this integrated in to CG. Are you thinking of integrating it yourself?

**Comment by timuric** [comment]
@iansilber Would be happy to accept a pull request as well as adding you as a contributor :)

**Comment by timuric** [comment]
@iansilber I have extracted `ReplaceManually` plugin and added to CG repo. Thanks!
